# Global Values
repoUrl: "https://github.com/Umesh-Pagar/test-argo.git"
targetRevision: HEAD
region: ""
account: ""
env: "dev"
namespace: "argocd"
clusters:
  - name: "in-cluster"
    url: "https://kubernetes.default.svc"
  - name: "aks-dev"
    url: "https://tech-mobile-dev-mq8wpbcl.hcp.eastus.azmk8s.io:443"
    
# Datadog Agent Values
datadogAgent:
  enable: true
  apiKeyExistingSecret: "datadog-api-key"
  site: "datadoghq.com"
  namespace: "datadog"

# External Secrets Operator
externalSecrets:
  enable: false
  namespace: "external-secrets"
  serviceAccountName: "external-secrets-sa"
  serviceAccountNamespace: "external-secrets"
  clientId: "f3e52f0b-8dea-4361-a36e-a53450701795"
  tenantId: "45d0c08e-3ba6-4272-9547-d08be59f03fc"
  keyVaultUrl: "https://kv-tech-mobile-dev.vault.azure.net/"
  secrets:
  - name: "secret1"
  - name: "db-password"

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:
  namespace: "cluster-autoscaler"

# nginx Values
ingressNginx:
  enable: true  
  namespace: "ingress-nginx"
  repoURL: "https://kubernetes.github.io/ingress-nginx"
  appVersion: 1.0
  controller:
    service:
      targetPorts:
        http: 80

# Metrics Server Values
metricsServer:
  enable: false
  targetRevision: 3.8.2
  namespace: "kube-system"