# Global Values
repoUrl: "https://github.com/Umesh-Pagar/test-argo.git"
targetRevision: HEAD
region: ""
account: ""
env: "dev"
namespace: "argocd"
clusters:
  - name: "in-cluster"
    url: "https://kubernetes.default.svc"
    
# Datadog Agent Values
datadogAgent:
  enable: true
  apiKeyExistingSecret: "datadog-api-key"
  site: "datadoghq.com"
  namespace: "datadog"

# External Secrets Operator
externalSecrets:
  enable: false
  namespace: "external-secrets"
  serviceAccountName: "external-secrets-sa"
  serviceAccountNamespace: "external-secrets"
  roleArn: "arn:aws:iam::123456789012:role/external-secrets-role"
  region: "us-east-1"
  # clientId: "28fc9472-a868-41f5-8e8f-8852eb42ee9d"
  # tenantId: "23e3a31f-e59d-4012-89a8-5e58b8eef10e"
  # keyVaultUrl: "https://kv-tech-mobile-dev-01.vault.azure.net/"
  secrets:
  - name: "datadog-api-key"

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:
  namespace: "cluster-autoscaler"

# nginx Values
ingressNginx:
  enable: true  
  namespace: "ingress-nginx"
  repoURL: "https://kubernetes.github.io/ingress-nginx"
  appVersion: 1.0
  controller:
    service:
      targetPorts:
        http: 80

# Metrics Server Values
metricsServer:
  enable: false
  targetRevision: 3.8.2
  namespace: "kube-system"