# Global Values
repoUrl: "https://github.com/Umesh-Pagar/test-argo.git"
targetRevision: HEAD
region: ""
account: ""
env: "dev"
namespace: "argocd"
clusters:
  - name: "in-cluster"
    url: "https://kubernetes.default.svc"

# Datadog Agent Values
datadogAgent:
  enable: true
  apiKeyExistingSecret: "datadog-api-key"
  site: "datadoghq.com"
  namespace: "datadog"

# nginx Values
ingressNginx:
  enable: true  
  namespace: "ingress-nginx"
  repoURL: "https://kubernetes.github.io/ingress-nginx"
  appVersion: 1.0
  controller:
    service:
      targetPorts:
        http: 80