apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.keyVaultUrl }}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: {{ .Values.name }}
        namespace: {{ .Values.namespace }}
  conditions:
    - namespaceSelector:
        matchLabels: {} #deploy to every namespace