apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.tenantId }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}