# Global Values
repoUrl: "https://github.com/Umesh-Pagar/test-argo.git"
targetRevision: HEAD
region: ""
account: ""
env: "dev"
namespace: "argocd"
clusters:
  - name: "eks"
    url: "https://kubernetes.default.svc"
    provider: "aws"
  - name: "aks"
    url: "https://tech-mobile-test-6qrrd9km.hcp.eastus.azmk8s.io:443"
    provider: "azure"

# Datadog Agent Values
datadogAgent:
  enable: true
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  namespace: "datadog"

# External Secrets Operator
externalSecrets:
  enable: true
  namespace: "external-secrets"

esoConfig:
  enable: true
  serviceAccountName: "external-secrets-sa"
  serviceAccountNamespace: "external-secrets"
  # Azure Configuration
  azure:
    clientId: "8984d07c-376b-445f-95d9-5f0cbb5662db"
    tenantId: "45d0c08e-3ba6-4272-9547-d08be59f03fc"
    keyVaultUrl: "https://kv-tech-mobile-test.vault.azure.net/"
  # AWS Configuration
  aws:
    roleArn: "arn:aws:iam::070818680311:role/eso-role"
    region: "us-east-1"
  secrets:
  - name: "test-secret"

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:
  namespace: "cluster-autoscaler"

# nginx Values
ingressNginx:
  enable: false  
  namespace: "ingress-nginx"
  repoURL: "https://kubernetes.github.io/ingress-nginx"
  appVersion: 1.0
  controller:
    service:
      targetPorts:
        http: 80

wiz:
  enable: false
  namespace: "wiz"
  targetRevision: 0.2.37

# Metrics Server Values
metricsServer:
  enable: false
  targetRevision: 3.8.2
  namespace: "kube-system"