apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: addons-secrets
  namespace: datadog
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    {{- if eq .Values.provider "azure" }}
    name: azure-secret-store
    {{- else if eq .Values.provider "aws" }}
    name: aws-secret-store
    {{- end }}
  target:
    name: addons-secrets
    creationPolicy: 'Owner'
  data:
  {{- range (fromJson .Values.secrets) }}
  - secretKey: {{ .secretKey }} # This key name will be used in the k8s secret
    remoteRef:
      key: {{ .name }}   # This is the key name in Azure Key Vault or AWS Secrets Manager path
  {{- end }}