apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    {{- if eq .Values.provider "azure" }}
    name: azure-secret-store
    {{- else if eq .Values.provider "aws" }}
    name: aws-secret-store
    {{- end }}
  target:
    name: datadog-api-key
    creationPolicy: 'Owner'
  data:
  - secretKey: datadog-api-key
    remoteRef:
      {{- if eq .Values.provider "azure" }}
      key: datadog-api-key  # Azure Key Vault key name
      {{- else if eq .Values.provider "aws" }}
      key: datadog/api-key  # AWS Secrets Manager path
      {{- end }}