apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: azure-exteral-secret
spec:
  externalSecretName: azure-secrets
  refreshTime: 3m
  namespaceSelectors:
  - matchLabels: {} #deploy to every namespace
  externalSecretSpec:
    refreshInterval: 3m
    secretStoreRef:
      kind: SecretStore
      name: azure-secret-store
    target:
      name: azure-secrets
      creationPolicy: 'Merge'
    data:
    {{- range .Values.secrets }}
    - secretKey: {{ .name }} # The key under which the secret will be stored in the Kubernetes secret.
      remoteRef:
        key: {{ .name }} # The key name in Azure Key Vault from which the secret value will be retrieved.
    {{- end }}

# ---

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: datadog-api-key
#   namespace: datadog
# spec:
#   refreshInterval: 3m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: azure-secret-store
#   target:
#     name: datadog-api-key
#     creationPolicy: 'Owner'
#   data:
#   - secretKey: api-key  # This key name will be used in the k8s secret
#     remoteRef:
#       key: datadog-api-key  # This is the key name in Azure Key Vault