{{- if .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    {{- if eq $.Values.provider "azure" }}
    name: azure-secret-store
    {{- else if eq $.Values.provider "aws" }}
    name: aws-secret-store
    {{- end }}
  target:
    name: {{ .name }}
    creationPolicy: 'Owner'
  data:
  - secretKey: {{ .key }}
    remoteRef:
      {{- if eq $.Values.provider "azure" }}
      key: {{ .remoteRef.azure }}
      {{- else if eq $.Values.provider "aws" }}
      key: {{ .remoteRef.aws }}
      {{- end }}
{{- end }}
{{- end }}