{{- if eq .Values.provider "azure" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.azure.keyVaultUrl }}
      authType: {{ .Values.azure.authType }}
      serviceAccountRef:
        name: {{ .Values.serviceAccountName }}
        namespace: {{ .Values.serviceAccountNamespace }}
  conditions:
  - namespaceSelector:
      matchLabels: {} #deploy to every namespace
{{- end }}

{{- if eq .Values.provider "aws" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
            namespace: {{ .Values.serviceAccountNamespace }}
  conditions:
  - namespaceSelector:
      matchLabels: {} #deploy to every namespace
{{- end }}