{{- if eq .Values.provider "azure" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.azure.tenantId | quote }}
      vaultUrl: {{ .Values.azure.keyVaultUrl | quote }}
      authType: {{ .Values.azure.authType | default "WorkloadIdentity" }}
      {{- if eq (.Values.azure.authType | default "WorkloadIdentity") "WorkloadIdentity" }}
      serviceAccountRef:
        name: {{ .Values.serviceAccountName | default "external-secrets-sa" }}
        namespace: {{ .Values.serviceAccountNamespace | default "external-secrets" }}
      {{- end }}
{{- end }}

{{- if eq .Values.provider "aws" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | default "us-east-1" | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName | default "external-secrets-sa" }}
            namespace: {{ .Values.serviceAccountNamespace | default "external-secrets" }}
{{- end }}