{{- if and (.Values.datadogAgent) (.Values.datadogAgent.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog-agent-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      {{- range .Values.clusters }}
      - cluster: {{ .name }}
        url: {{ .url }}
      {{- end }}
  template:
    metadata:
      name: '{{`{{.cluster}}`}}-datadog'
    spec:
      project: "default"
      source:
        repoURL: {{ .Values.repoUrl }}
        path: cluster-addons/add-ons/datadog-agent
        targetRevision: {{ .Values.targetRevision }}
        helm:
          parameters:
            - name: "datadog.apiKeyExistingSecret"
              value: {{ .Values.datadogAgent.apiKeyExistingSecret }}
            - name: "datadog.site"
              value: {{ .Values.datadogAgent.site }}
            - name: "datadog.clusterName"
              value: '{{`{{.cluster}}`}}'
      destination:
        server: '{{`{{.url}}`}}'
        namespace: {{ .Values.datadogAgent.namespace }}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
{{- end -}}