apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.serviceAccountNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{- if eq .Values.provider "azure" }}
    # Azure Workload Identity annotations
    azure.workload.identity/client-id: {{ .Values.azure.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.tenantId }}
    {{- end }}
    {{- if eq .Values.provider "aws" }}
    # AWS IRSA annotations
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
    {{- end }}